apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: siaknng-auth-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: siaknng-auth
  template:
    metadata:
      labels:
        app: siaknng-auth
    spec:
      containers:
        - name: siaknng-auth-container
          image: siaknngregistry.azurecr.io/auth:1.0.5
          ports:
          - containerPort: 80
          env:
            - name: SECRET_KEY
              value: "f3t^9es$l+!6y4qjrl+^_8$z$-2as4kkoj=ly36)^vph9_!z(j"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: POSTGRES_HOST
              value: postgres-auth
            - name: POSTGRES_NAME
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-credentials
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: siaknng-auth-service
spec:
  selector:
    app: siaknng-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: siaknng-auth-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: siaknng-auth-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

---

apiVersion: batch/v1
kind: Job
metadata:
  name: siaknng-auth-migration
spec:
  template:
    spec:
      containers:
        - name: siaknng-auth-migration-container
          image: siaknngregistry.azurecr.io/auth:1.0.5
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: SECRET_KEY
              value: "f3t^9es$l+!6y4qjrl+^_8$z$-2as4kkoj=ly36)^vph9_!z(j"
            - name: POSTGRES_HOST
              value: postgres-auth
            - name: POSTGRES_NAME
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-credentials
                  key: password
      restartPolicy: Never
  backoffLimit: 5
